In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# Mean of dataset

In [5]:
l = [76,54,65,34,87]

In [6]:
np.mean(l)

63.2

In [7]:
np.mean([64,65,34,87,98,54])

67.0

In [9]:
np.sum([54,6,5,76,34,65])

240

In [12]:
np.sqrt(54)

7.3484692283495345

In [14]:
np.square(67)

4489

In [15]:
# 1d

In [16]:
l = [1,2,3,4,5]

In [18]:
l = np.array(l)

In [19]:
l

array([1, 2, 3, 4, 5])

In [20]:
np.ndim(l)

1

In [21]:
l2 = [[1,2,3,4,5],[10,20,30,40,50]]

In [22]:
np.array(l2)

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [23]:
l2 = np.array(l2)

In [24]:
l2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [25]:
np.ndim(l2)

2

In [26]:
l3 = [[[1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500]]]

In [27]:
l3 = np.array(l3)

In [28]:
l3

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50],
        [100, 200, 300, 400, 500]]])

In [29]:
np.ndim(l3)

3

In [30]:
np.random.randint(1,10, 5) #Low, max, count/size

array([2, 7, 2, 4, 1])

In [31]:
np.random.randint(1,50, 8)

array([49, 40, 39, 24, 46, 20, 32, 34])

In [33]:
np.random.random([5,3])

array([[0.95599695, 0.17958749, 0.08336421],
       [0.15972712, 0.92656435, 0.00287751],
       [0.30020421, 0.03804977, 0.59197229],
       [0.72849351, 0.67237312, 0.3891596 ],
       [0.44893979, 0.82782606, 0.71216246]])

In [35]:
np.random.rand(2,2,3)

array([[[0.79998471, 0.98070764, 0.95793264],
        [0.85098656, 0.69192091, 0.70964537]],

       [[0.28061577, 0.43915227, 0.80725545],
        [0.95611477, 0.52484486, 0.28858226]]])